FROM continuumio/anaconda:5.0.1
RUN apt-get update
RUN apt-get install -y --no-install-recommends apt-utils
RUN apt-get install -y --reinstall build-essential
RUN apt-get install -y gsl-bin
RUN apt-get install -y libgsl0-dbg
RUN apt-get install -y libgsl0-dev
RUN git clone https://github.com/tansey/gfl
RUN cd gfl/cpp && make all
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/gfl/cpp/lib/
RUN /bin/bash -c 'source $HOME/.bashrc'
RUN cd gfl/ && python setup.py build && python setup.py install
