FROM continuumio/anaconda
RUN apt update
RUN apt -y install --reinstall build-essential
RUN apt -y install gsl-bin
RUN apt -y install libgsl0-dbg
RUN apt -y install libgsl0-dev
RUN git clone https://github.com/tansey/gfl
RUN cd gfl/cpp && make clean && make all
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/gfl/cpp/lib/
RUN /bin/bash -c 'source $HOME/.bashrc'
RUN cd gfl/ && python setup.py build && python setup.py install