FROM continuumio/anaconda:5.0.1
RUN apt-get update
# RUN apt-get -y install --reinstall build-essential
RUN apt-get -y install gsl-bin
RUN apt-get -y install libgsl0-dbg
RUN apt-get -y install libgsl0-dev
# RUN git clone https://github.com/tansey/gfl
# RUN cd gfl/cpp && make clean && make all
# ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/gfl/cpp/lib/
# RUN /bin/bash -c 'source $HOME/.bashrc'
# RUN cd gfl/ && python setup.py build && python setup.py install
RUN pip install --upgrade pip
RUN pip install pygfl
